---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-custom
# description will be included in the image's metadata
description: A Custom image for my personal use with batteries included

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
        - AtkinsonHyperlegibleMono
        - CascadiaCode
        - CommitMono
        - Cousine
        - DejaVuSansMono
        - DroidSansMono
        - FiraCode
        - FiraMono
        - Hack
        - Hasklig
        - iA-Writer
        - Inconsolata
        - JetBrainsMono
        - Lekton
        - Lilex
        - Mononoki
        - Noto
        - ProFont
        - SourceCodePro
        - SpaceMono
        - Ubuntu
        - UbuntuMono
        - UbuntuSans
        - NerdFontsSymbolsOnly
      google-fonts:
        - Atkinson Hyperlegible

  - type: dnf
    repos:
      cleanup: true
      files:
        - https://repository.mullvad.net/rpm/beta/mullvad.repo
      copr:
        - alternateved/keyd
    optfix:
      - Mullvad VPN
    install:
      skip-unavailable: true
      packages:
        - repo: mullvad-beta
          packages:
            - mullvad-vpn
        - repo: copr:copr.fedorainfracloud.org:alternateved:keyd
          packages:
            - keyd
        - sysstat
        - neovim
        - python3-neovim
        - wireshark
        #TODO: replace the opensnitch install with a module that pulls the latest arbitrary release
        - https://github.com/evilsocket/opensnitch/releases/download/v1.7.0.0/opensnitch-1.7.0.0-1.x86_64.rpm
        - https://github.com/evilsocket/opensnitch/releases/download/v1.7.0.0/opensnitch-ui-1.7.0.0-1.noarch.rpm

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
