---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-custom
# description will be included in the image's metadata
description: A Custom image for my personal use with batteries included

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
        - AtkinsonHyperlegibleMono
        - CascadiaCode
        - CommitMono
        - Cousine
        - DejaVuSansMono
        - DroidSansMono
        - FiraCode
        - FiraMono
        - Hack
        - Hasklig
        - iA-Writer
        - Inconsolata
        - JetBrainsMono
        - Lekton
        - Lilex
        - Mononoki
        - Noto
        - ProFont
        - SourceCodePro
        - SpaceMono
        - Ubuntu
        - UbuntuMono
        - UbuntuSans
        - NerdFontsSymbolsOnly
      google-fonts:
        - Atkinson Hyperlegible

  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/beta/mullvad.repo
      - https://copr.fedorainfracloud.org/coprs/alternateved/keyd/repo/fedora-%OS_VERSION%/alternateved-keyd-fedora-%OS_VERSION%.repo
    optfix:
      - Mullvad VPN
    install:
      - mullvad-vpn
      - keyd
      - sysstat
      - fd-find
      - neovim
      - python3-neovim
      - wireshark
      - nmap

  - type: opensnitch
    # needed?
    source: local
    apples: true


  - type: systemd
    system:
      masked:
        - brew-setup.service
        - brew-update.timer
        - brew-upgrade.timer
      enabled:
        - keyd.service
        - opensnitch.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
